### ISSUE TITLE
Uploading large image does not work, and presents no error

### ISSUE THREAD

**Issue by srchulo** [manuelgeek/vuejs-medium-editor#20]
Whenever I upload a large image, no request goes out to imgur and nothing ever happens-- it seems to fail silently.

**Comment by srchulo** [comment]
It looks like the limit is 10MB. It would be great if there was a way to handle errors, like a callback. Then I could toast something like "Image must be smaller than 10 MB":

https://github.com/manuelgeek/vuejs-medium-editor/blob/97a28f4534938467cfa3ea4d8db950b3b73de563/src/libs/Embed/InsertImage.vue#L11

**Comment by tracykoay** [comment]
> It looks like the limit is 10MB. It would be great if there was a way to handle errors, like a callback. Then I could toast something like "Image must be smaller than 10 MB":
> 
> https://github.com/manuelgeek/vuejs-medium-editor/blob/97a28f4534938467cfa3ea4d8db950b3b73de563/src/libs/Embed/InsertImage.vue#L11

did you found any solution for this issues?

**Comment by srchulo** [comment]
@tracykoay I did not

**Comment by manuelgeek** [comment]
this is an issue with the `vue-upload-library' . see https://github.com/lian-yue/vue-upload-component/issues/318
I added ability to change upload size

**Comment by srchulo** [comment]
Great, thanks!
