### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Haga14** [manuelgeek/vuejs-medium-editor#27]
I attempted to play around with the the demo at https://manuelgeek.github.io/vuejs-medium-editor/

However, when I type fast or press delete/control-delete in freezes and starts cranking up my processor (fan turns on immidiately). 

Also, following the setup example doesn't guide in the readme produces something vastly different to what's in the demo. Could you provide the code for the demo as an example?

Thanks for making this!

**Comment by manuelgeek** [comment]
@Haga14 the docs have been updated
