### ISSUE TITLE
Webpack: These relative modules were not found

### ISSUE THREAD

**Issue by ferretwithaberet** [manuelgeek/vuejs-medium-editor#50]
```
* ../../assets/icons/image-align-expand-active.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
* ../../assets/icons/image-align-expand.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
* ../../assets/icons/image-align-full-active.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
* ../../assets/icons/image-align-full.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
* ../../assets/icons/image-align-normal-active.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
* ../../assets/icons/image-align-normal.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"44fd2dcf-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuejs-medium-editor/src/libs/Embed/ImagePosition.vue?vue&type=template&id=e1bd8472&
```

**Comment by manuelgeek** [comment]
@ferretwithaberet could you give a detailed info and how to recreate this?

**Comment by ferretwithaberet** [comment]
> @ferretwithaberet could you give a detailed info and how to recreate this?

Was trying to replace `vue2-medium-editor` with this package. After I installed this package I tried importing and using it, that is when it errored. I looked in the `node_modules` folder of this package and it had no `assets` folder if that was supposed to be there.

I installed this package with `yarn` if that is somehow relevant.
The issue might also be related to my webpack config.

Cannot give exact code as it happened in a project at work.

**Comment by manuelgeek** [comment]
There's no `assets` in the library, this seems not to be related with this

**Comment by ferretwithaberet** [comment]
> There's no `assets` in the library, this seems not to be related with this

[Are you sure?](https://github.com/manuelgeek/vuejs-medium-editor/tree/master/src/assets/icons)

**Comment by manuelgeek** [comment]
Let me try recreating it, i'll get back

**Comment by ferretwithaberet** [comment]
There is also something wrong with how this package gets published to NPM, as I get all the files instead of just the `dist/` folder like it is supposed to work.

The `assets/` folder is not in the `dist/` folder. That might be the issue.

![Uploading image.png…]()

**Comment by manuelgeek** [comment]
@ferretwithaberet the dist folder caries the example app, check the package.json, the. entry point to the library is ./src/Editor.vue
check at the demo on github pageshttps://manuelgeek.github.io/vuejs-medium-editor/ the errors you raised are not on the console

**Comment by ferretwithaberet** [comment]
> @ferretwithaberet the dist folder caries the example app, check the package.json, the. entry point to the library is ./src/Editor.vue check at the demo on github pageshttps://manuelgeek.github.io/vuejs-medium-editor/ the errors you raised are not on the console

The errors I posted are webpack errors, they are not supposed to be in the browser console. The whole build using webpack fails. The build works with `vue2-medium-editor` though.

**Comment by manuelgeek** [comment]
@ferretwithaberet , aaaah, I see. seems the images are corrupted, i can't open them locally either, let me fix that

**Comment by manuelgeek** [comment]
@ferretwithaberet check latest version 1.2.3

**Comment by ferretwithaberet** [comment]
It still errors when I try to use it. Can you try to test it yourself with a `vue create <project_name>` project?

You can install the package with a local path using NPM to be able to test it before publishing it.

```Error: ENOENT: no such file or directory, open '/home/ferretwithaberet/Projects/PATH/TO/PROJECT/node_modules/vuejs-medium-editor/src/assets/icons/image-align-expand-active.png'```

@manuelgeek

**Comment by manuelgeek** [comment]
The example app is a vue cli app, and the icon you're referring to exists

**Comment by ferretwithaberet** [comment]
Then I do not know what is happening, I will try to test when I get home.

**Comment by manuelgeek** [comment]
it's OK,
maybe, are you using vue 3 or 2?

I'll also be checking it later. will let you know

**Comment by ferretwithaberet** [comment]
> it's OK,
> maybe, are you using vue 3 or 2?
> 
> I'll also be checking it later. will let you know

Using Vue 2.

**Comment by manuelgeek** [comment]
still don't see the issue, can you try the v.1.2.5 i juts published?

**Comment by ferretwithaberet** [comment]
> still don't see the issue, can you try the v.1.2.5 i juts published?

This is what gets installed when I run `yarn add vuejs-medium-editor`. There is no `dist/` and no `aseets/` folder. Something is wrong with the `package.json`.
![image](https://user-images.githubusercontent.com/46427158/135613895-3b54bddf-2e8b-43b7-99d9-2e1531fa0a8d.png)

**Comment by manuelgeek** [comment]
yeah, i even tried adding the path to the images, they get uploaded to npm
```
notice 
npm notice 📦  vuejs-medium-editor@1.2.6
npm notice === Tarball Contents === 
npm notice 6.1kB src/.DS_Store                                 
npm notice 6.1kB src/assets/.DS_Store                          
npm notice 1.1kB LICENSE                                       
npm notice 7.8kB src/themes/default.css                        
npm notice 135B  src/main.js                                   
npm notice 2.4kB package.json                                  
npm notice 5.9kB README.md                                     
npm notice 1.2kB src/assets/icons/image-align-expand-active.png
npm notice 1.2kB src/assets/icons/image-align-expand.png       
npm notice 1.1kB src/assets/icons/image-align-full-active.png  
npm notice 1.1kB src/assets/icons/image-align-full.png         
npm notice 1.2kB src/assets/icons/image-align-normal-active.png
npm notice 1.2kB src/assets/icons/image-align-normal.png       
npm notice 6.8kB src/assets/logo.png                           
npm notice 7.0kB src/App.vue                                   
npm notice 3.8kB src/Editor.vue                                
npm notice 0     src/libs/EditorMode.vue                       
npm notice 566B  src/libs/Embed/ImageHandler.vue               
npm notice 1.5kB src/libs/Embed/ImagePosition.vue              
npm notice 7.4kB src/libs/InsertEmbed.vue                      
npm notice 4.2kB src/libs/Embed/InsertGist.vue                 
npm notice 5.2kB src/libs/Embed/InsertImage.vue                
npm notice 2.1kB src/libs/ListHandler.vue                      
npm notice 1.1kB src/libs/ReadMode.vue                         
npm notice === Tarball Details === 
npm notice name:          vuejs-medium-editor                     
npm notice version:       1.2.6                                   
npm notice package size:  23.2 kB                                 
npm notice unpacked size: 76.3 kB                                 
npm notice shasum:        595c737590abc6fae37224ecba649e2577212252
npm notice integrity:     sha512-SNuNDRduYIQ9M[...]THDw9n1/Ot5og==
npm notice total files:   24                                      
npm notice 
+ vuejs-medium-editor@1.2.6

```

**Comment by manuelgeek** [comment]
don't know if the above will bring any effect

**Comment by ferretwithaberet** [comment]
The problem is that there is no `dist/` folder uploaded to NPM, you only upload the `src/` folder.

**Comment by manuelgeek** [comment]
the dist dir is not related to the project at all, that holds the build files for the example app, - the entry point is the editor.vue
