### ISSUE TITLE
Nice wrapper, but it seems to be broken.

### ISSUE THREAD

**Issue by hebertlima** [manuelgeek/vuejs-medium-editor#69]
After following all the installation steps, it seems to be working, but in the console, I got a lot of strange errors. 

Right after loading the page:
![image](https://user-images.githubusercontent.com/34013325/212525252-ede32a71-524e-4fd5-86af-5158e798bd4d.png)

Lead to this part:
![image](https://user-images.githubusercontent.com/34013325/212525383-eadc9dcb-e611-4991-80fa-f3b5989f71bd.png)

When I type something inside the editor, I get another error.
![image](https://user-images.githubusercontent.com/34013325/212525422-137159c7-9537-4f75-8daa-38b0f5359e68.png)

This one leads me to this:
![image](https://user-images.githubusercontent.com/34013325/212525467-7c323893-c225-422c-a808-e653ef366340.png)

Inside this component, I have a button with this code:
```js
back() {
    Inertia.get(route('articles.index'))
}
```

If I click, another error:
![image](https://user-images.githubusercontent.com/34013325/212525548-20ed8472-9737-4ede-acbc-838e0bf52e1c.png)

Leads to this:
![image](https://user-images.githubusercontent.com/34013325/212525677-6d552d82-c388-49bd-8f5a-8a4549091c29.png)

 
here is the code:

```js
import MediumEditor from 'vuejs-medium-editor'
import 'medium-editor/dist/css/medium-editor.css'
import 'vuejs-medium-editor/src/themes/default.css'

# template
<MediumEditor :options='options' v-model="form.content" :prefill='form.defaultValue' :hide-gist="false" :hideImage="false" :onChange="onChange" />
<button @click="back">Back</button>
```

```js
# inside data(){}
coverPreview: null,
form: {
	content: null,
	defaultValue: `<h1><br /></h1>`,
},
options: {
	uploadUrl: "https://api.imgur.com/3/image",
	uploadUrlHeader: { 'Authorization': 'Client-ID a3tw6ve4wss3c' },
	file_input_name: "image",
	file_size: 1024 * 1024 * 10,
	imgur: true,
	buttonLabels: 'fontawesome',
	targetBlank: true,
	placeholder: {
		hideOnClick: false,
	},
	toolbar: {
		buttons: ["bold", "italic", "underline", "strikethrough", "h1", "h2", 'unorderedlist', 'orderedlist', "indent", "outdent", 'anchor', {
			name: 'image',
			action: 'image',
			aria: 'insert image from url',
			tagNames: ['img'],
			contentDefault: '<b>image</b>',
			contentFA: '<i class="fa fa-picture-o"></i>'
		}]
	},
}
```

```js
I am using Laravel 8 with Inertia and Vue 3:

"vue-loader": "^17.0.1",
"@vue/compiler-sfc": "^3.2.45",
"@vuelidate/core": "^2.0.0",
"@inertiajs/inertia": "^0.11.0",
"@inertiajs/inertia-vue3": "^0.6.0",
"vue": "^3.2.31"
"vuejs-medium-editor": "^1.2.6"
```

Did anyone manage to use it? Every help is welcome 🧑🏾‍💻

**Comment by manuelgeek** [comment]
@hebertlima I've not tried any Vue 3 support for this, I can check it out, if you do a fix, a PR is welcome

**Comment by manuelgeek** [comment]
@hebertlima I just did a release to support version 3
check at README.md file for instructions

https://www.npmjs.com/package/vuejs-medium-editor
