### ISSUE TITLE
Feature request: add ability to embed videos

### ISSUE THREAD

**Issue by gileneusz** [manuelgeek/vuejs-medium-editor#70]
I wanted to suggest a feature request for the plugin: the ability to embed videos, whether embedded from YouTube or from a public folder. Right now, we can embed images, but I think having the ability to embed videos would be a great addition.

This feature would make the editor more versatile and user-friendly, allowing users to easily include video content in their text, regardless of the source. It would be a big win for anyone looking to create content-rich experiences with your plugin,

Thanks for your work on this plugin!

**Comment by manuelgeek** [comment]
@gileneusz I'll look into it, thanks
