### ISSUE TITLE
Remove or disable the insert-image-container

### ISSUE THREAD

**Issue by Attacler** [manuelgeek/vuejs-medium-editor#72]
Hi there,

Is it possible to disable the insert-image-container?
(the plus sign infront of the line that your typing in that allows for image/video upload and code snippets)

**Comment by manuelgeek** [comment]
Hello @Attacler ,
There's a prop `:hide-image="false"` that you could use.
Also, you can remove the append image in toolbar by removing it in the options.

I don't If this answers you
