### ISSUE TITLE
Restore text after editing

### ISSUE THREAD

**Issue by kozubov** [manuelgeek/vuejs-medium-editor#74]
I use medium editor in vue2 component.
`<medium-editor` :prefill="text2"
                     v-model="content"
                     :options="options"
                     :hideImage="true"
                     :hideGist ="true"
                     :hideVideo  ="true"
                     `:onChange="onChange"/>`
where:
text = props, 
text2 = text.

I need to cleaer and restore text by button click to 'text'. 
When I try to make this.content = this.text or this.content = '' the 'content' still not refresh.
How can I do this.

**Comment by manuelgeek** [comment]
@kozubov When you're passing the default value, use the `prefill` prop and not `v-model` to set.
There's a pending task #57 that will sheep in the coming days. You can follow the issue to get updated.
For now, use; 
`this.prefill = this.text`

**Comment by kozubov** [comment]
@manuelgeek 
v-model="content" adding paragraph tags  in the start and in the end  to v-model

**Comment by manuelgeek** [comment]
@kozubov that's the default empty state of the editor
