### ISSUE TITLE
Delete included content <p><br></p>

### ISSUE THREAD

**Issue by dapehe94** [manuelgeek/vuejs-medium-editor#79]
Hello
When you delete all content there are always these html tags left `<p><br></p>`.
Is there any way that when you delete everything, the content is completely empty?
Thanks

**Comment by mrcego** [comment]
Just create an computed and pass value from v-model value to striptags: https://www.npmjs.com/package/striptags

**Comment by manuelgeek** [comment]
@dapehe94 you could striptags as suggested by @mrcego or just add a check to treat that value as null since that's coming from `medium-editor` itself
